### ISSUE TITLE
Cache all problemsets failed with codeforces api error

### ISSUE THREAD

**Issue by ParsaAlizadeh** [ParsaAlizadeh/TLE#9]
After running `;cache problemsets all`, there are many errors in this format
```
WARNING:tle.util.codeforces_api:CF API did not respond with JSON, status 503.
WARNING:ProblemsetCache:Problemset fetch failed for contest 1503. CodeforcesApiError('Codeforces API error')
```

**Comment by SajidZakaria** [comment]
Same case with `;cache ratingchanges all`. I wonder if the rate of queries could be limited, so that CF api doesn't stop responding(if that's the case). But this task is blocking, and since tle runs on only one thread, this would take a lot of time, better to do it on silent hours, and it's only needed to be done once.
